version: "3"
services: 
  scan-process:
    container_name: scan-process
    # restart: always
    build: .
    ports: 
      - "7500:7500"
    links: 
      - mongo
  mongo: 
    container_name: mongo_db
    image: circleci/mongo:4.4.2
    ports:
      - "27017:27017"
    volumes: 
      - "./mongo/db:/data/db"